# Dockerfile.backend
FROM python:3.10-slim

RUN apt-get update && apt-get install -y supervisor && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY backend/requirements.txt requirements.txt
RUN pip install --upgrade pip && pip install -r requirements.txt
COPY backend/ .

COPY backend/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

EXPOSE 5000
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
